"use strict";

const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./routes/*.routes.js"];

const doc = {
  // openapi: "3.0.1",
  info: {
    title: "ALQUIPET REST SERVER DOCUMENTATION",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module for the ALQUIPET REST API.",
    termsOfService: "http://swagger.io/terms/",
    contact: {
      email: "apiteam@swagger.io",
    },
    license: {
      name: "Apache 2.0",
      url: "http://www.apache.org/licenses/LICENSE-2.0.html",
    },
    version: "1.0.0",
  },
  externalDocs: {
    description: "Find out more about Swagger",
    url: "http://swagger.io",
  },
  host: "localhost:8081",
  basePath: "/api",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  servers: [
    {
      url: "http://localhost:8081",
    },
    {
      url: "https://www.alquipet.com",
    },
  ],
  tags: [
    {
      name: "Auth",
      description: "Endpoints about Authentication with Oauth2.0 + JWT",
      externalDocs: {
        description: "Find out more",
        url: "https://oauth.net/2/",
      },
    },
    {
      name: "Listing",
      description: "Endpoints about Listing´s CRUD",
    },
    {
      name: "User",
      description: "Endpoints about Users´s CRUD",
    },
  ],

};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app.js");
});
